name: flutter_load_kit
description: A package that contains reusable animated loading indicators.
version: 0.0.2
homepage: https://github.com/Xclusivecyborg/flutter_loadkit
repository: https://github.com/Xclusivecyborg/flutter_loadkit

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
